// vite-svelte-ts/src/App.svelte
<script lang="ts">
	import svelteLogo from "./assets/svelte.svg";
	import breadboardLogo from "./assets/breadboard.png";
	import viteLogo from "/vite.svg";
	import Breadboard from "./lib/Breadboard.svelte";
</script>

<main>
	<div>
		<a href="https://vitejs.dev" target="_blank" rel="noreferrer">
			<img src={viteLogo} class="logo" alt="Vite Logo" />
		</a>
		<a href="https://svelte.dev" target="_blank" rel="noreferrer">
			<img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
		</a>
		<a href="https://breadboard-ai.github.io/breadboard/" target="_blank">
			<img src={breadboardLogo} class="logo breadboard" alt="Breadboard logo" />
		</a>
	</div>
	<h1>Vite + Svelte + Breadboard</h1>

	<div class="card">
		<Breadboard />
	</div>

	<p class="read-the-docs">Click on the Vite, Svelte and Breadboard logos to learn more</p>
</main>

<style>
	.logo {
		height: 6em;
		padding: 1.5em;
		will-change: filter;
		transition: filter 300ms;
	}
	.logo:hover {
		filter: drop-shadow(0 0 2em #646cffaa);
	}
	.logo.svelte:hover {
		filter: drop-shadow(0 0 2em #ff3e00aa);
	}

	.logo.breadboard:hover {
		filter: drop-shadow(0 0 2em #ffac04aa);
	}
	.read-the-docs {
		color: #888;
	}
</style>

// vite-vue-ts/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
     <a href="https://breadboard-ai.github.io/breadboard/" target="_blank">
      <img src="./assets/breadboard.png" class="logo breadboard" alt="Breadboard logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue + Breadboard" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}

.logo.vue:breadboard {
  filter: drop-shadow(0 0 2em #FFFFFFaa);
}
</style>
