// vite/react-ts/src/App.tsx
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import breadboardLogo from "../../../assets/breadboard.png";
import "./App.css";
import board, { inputAttribute } from "./breadboard";
import { useState } from "react";

function App() {
  const [message, setMessage] = useState("");

  const displayValue = async () => {
    for await (const run of board.run()) {
      if (run.type === "input") {
        run.inputs = {
          [inputAttribute]: "Hello from Breadboard",
        };
      } else if (run.type === "output") {
        const output = run.outputs;
        setMessage(JSON.stringify(output["message"], null));
      }
    }
  };

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img
            src={breadboardLogo}
            className="logo breadboard"
            alt="Breadboard logo"
          />
        </a>
      </div>
      <h1>Vite + React + Breadboard</h1>
      <div className="card">
        <button onClick={displayValue}>
          Click here to get a message from Breadboard
        </button>
        <p>{message}</p>
      </div>
    </>
  );
}

export default App;

// vite-svelte-ts/src/App.svelte
<script lang="ts">
	import svelteLogo from "./assets/svelte.svg";
	import breadboardLogo from "./assets/breadboard.png";
	import viteLogo from "/vite.svg";
	import Breadboard from "./lib/Breadboard.svelte";
</script>

<main>
	<div>
		<a href="https://vitejs.dev" target="_blank" rel="noreferrer">
			<img src={viteLogo} class="logo" alt="Vite Logo" />
		</a>
		<a href="https://svelte.dev" target="_blank" rel="noreferrer">
			<img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
		</a>
		<a href="https://breadboard-ai.github.io/breadboard/" target="_blank">
			<img src={breadboardLogo} class="logo breadboard" alt="Breadboard logo" />
		</a>
	</div>
	<h1>Vite + Svelte + Breadboard</h1>

	<div class="card">
		<Breadboard />
	</div>

	<p class="read-the-docs">Click on the Vite, Svelte and Breadboard logos to learn more</p>
</main>

<style>
	.logo {
		height: 6em;
		padding: 1.5em;
		will-change: filter;
		transition: filter 300ms;
	}
	.logo:hover {
		filter: drop-shadow(0 0 2em #646cffaa);
	}
	.logo.svelte:hover {
		filter: drop-shadow(0 0 2em #ff3e00aa);
	}

	.logo.breadboard:hover {
		filter: drop-shadow(0 0 2em #ffac04aa);
	}
	.read-the-docs {
		color: #888;
	}
</style>
